"""
Deterministic scoring engine.

All arithmetic happens HERE, in code, at data-load time - never inside the LLM.
Original text values stay untouched for the model to read; this module derives
numbers internally, computes market scores / tiers / city roles / conflicts,
and the results are injected into the context as [DERIVED] conclusions.
"""
from __future__ import annotations
import re
from .schema import SCORING
from .parser import split_list, _clean, _is_missing


def _lvl(v) -> float | None:
    return SCORING["level_map"].get(_clean(v).lower())


def _pct(v) -> float | None:
    m = re.search(r"([+-]?\d+(?:\.\d+)?)\s*%", _clean(v))
    return float(m.group(1)) if m else None


def _num(v) -> float | None:
    try:
        return float(_clean(v))
    except ValueError:
        return None


def market_scores(tables: dict) -> list[dict]:
    b = tables.get("B_Markets") or []
    c = {}
    for row in (tables.get("C_Products") or []):
        c.setdefault(_clean(row.get("Market")).lower(), []).append(row)
    uvs = [_num(r.get("Search UV Index")) for r in b]
    max_uv = max([u for u in uvs if u is not None], default=None)
    grs = [_pct(r.get("Search Growth vs Baseline")) for r in b]
    max_gr = max([g for g in grs if g is not None], default=None)

    rows = []
    for r, uv, gr in zip(b, uvs, grs):
        mkt = _clean(r.get("Market"))
        notes, missing = [], []
        uv_n = ((uv / max_uv) if max_uv else 0.0) if uv is not None else None
        if uv is None:
            missing.append("Search UV Index")
        gr_n = ((gr / max_gr) if max_gr else 0.0) if gr is not None else None
        if gr is None:
            missing.append("Search Growth vs Baseline")

        product_rows = c.get(mkt.lower(), [])
        if len(product_rows) != 1:
            missing.append("unique C_Products row")
        crow = product_rows[0] if len(product_rows) == 1 else {}
        wsum, acc, parts, product_missing = 0.0, 0.0, [], []
        for col, w in SCORING["product_weights"].items():
            lv = _lvl(crow.get(col))
            if lv is not None:
                acc += w * lv
                wsum += w
                abbr = SCORING.get("product_abbr", {}).get(col, col.split()[0][:4].upper())
                parts.append(f"{abbr} {lv:g}")
            else:
                product_missing.append(col)
        if product_missing:
            missing.extend(product_missing)
        prod_n = (acc / wsum / 3) if wsum and not product_missing else None

        dw = SCORING["dim_weights"]
        if missing:
            score, tier = None, "NEEDS DATA"
            notes.append("score withheld - missing/ambiguous: " + ", ".join(dict.fromkeys(missing)))
        else:
            score = dw["uv"] * uv_n + dw["growth"] * gr_n + dw["product"] * prod_n
            th = SCORING["tier_thresholds"]
            tier = "P0" if score >= th["P0"] else ("P1" if score >= th["P1"] else "P2")
            hotel, flight = _lvl(crow.get("Hotel Conversion")), _lvl(crow.get("Flight Demand"))
            cap = SCORING["safety_cap_level"]
            if hotel <= cap and flight <= cap and tier != "P2":
                tier = "P2"
                notes.append("safety cap: hotel & flight conversion signals both weak")
        rows.append({"market": mkt,
                     "uv_norm": round(uv_n, 2) if uv_n is not None else None,
                     "growth_norm": round(gr_n, 2) if gr_n is not None else None,
                     "product_norm": round(prod_n, 2) if prod_n is not None else None,
                     "breakdown": " ".join(parts),
                     "score": round(score, 2) if score is not None else None,
                     "tier": tier, "notes": "; ".join(notes)})
    return rows


def scores_md(rows: list[dict], collapse_methodology: bool = False) -> str:
    dw, pw = SCORING["dim_weights"], SCORING["product_weights"]
    th = SCORING["tier_thresholds"]
    p0_count = sum(r.get("tier") == "P0" for r in rows)
    ranked_count = sum(r.get("score") is not None for r in rows)
    head = ("Generated by the prototype from the input tables using configurable rules - "
            "this table is NOT part of the original source data.\n"
            f"Score = {dw['uv']}*UV_norm + {dw['growth']}*Growth_norm + "
            f"{dw['product']}*Product_norm; product mix weights: "
            + ", ".join(f"{k.split()[0]} {v}" for k, v in pw.items())
            + f"; tiers: P0 requires score >= {th['P0']}, P1 requires >= {th['P1']}, below that P2.\n"
            f"Threshold result: {p0_count} of {ranked_count} markets with complete inputs are P0. "
            "The fixed cut-points do not enforce a resource-capacity target. They are configurable "
            "defaults with no historical calibration; "
            "production alternatives: quantile-based cuts, resource-count top-N, or ROI-calibrated "
            "thresholds - or present a ranked list and let the PM draw the line.\n"
            "Basis of weights [ASSUMPTION - not calibrated from data]: the campaign objective "
            "(table A) is demand capture + conversion, so current demand level (UV) carries the "
            "largest dimension weight, conversion capability (product mix) second, momentum "
            "(growth) third. Product-line weights mirror transaction value roles: hotel highest "
            "(core GMV and the objective's conversion metric), flight second (trip trigger), "
            "attractions/tours mid (add-on revenue), train/transfer lowest (auxiliary). "
            "Tier thresholds are set to separate this round's score distribution and have no "
            "historical calibration. All values are configurable defaults: before production use "
            "they should be calibrated against past campaign performance per market, or set by "
            "the Campaign Ops PM per objective.\n")
    if collapse_methodology:
        head = ("<details>\n<summary>Scoring methodology</summary>\n\n"
                + head.strip() + "\n\n</details>\n")
    lines = ["| Market | UV_norm | Growth_norm | Product_norm (mix) | Score | Tier |",
             "|---|---|---|---|---|---|"]
    for r in sorted(rows, key=lambda x: (x["score"] is None, -(x["score"] or 0))):
        uv = "—" if r["uv_norm"] is None else r["uv_norm"]
        growth = "—" if r["growth_norm"] is None else r["growth_norm"]
        product = "—" if r["product_norm"] is None else r["product_norm"]
        score = "—" if r["score"] is None else r["score"]
        lines.append(f"| {r['market']} | {uv} | {growth} | "
                     f"{product} ({r['breakdown']}) | {score} | {r['tier']} |")
    return head + "\n".join(lines)


def city_roles(tables: dict, market: str) -> list[dict]:
    """Two-layer mapping: Interest City (from B, what users actually search) vs
    Readiness Cluster (from D, how supply data is grouped). A cluster row NEVER
    implies interest in all its member cities - only the searched city is
    recommended; other members are 'same-cluster extension candidates'."""
    from .context import _city_match
    b = [r for r in (tables.get("B_Markets") or [])
         if _clean(r.get("Market")).lower() == market.lower()]
    if not b:
        return []
    interest = split_list(b[0].get("Top City Interest Signals", ""))
    d_rows = tables.get("D_Cities") or []
    out = []
    for city in interest:
        d = next((r for r in d_rows if _city_match(r.get("City / Cluster", ""), [city])), None)
        if d is None:
            out.append({"city": city, "cluster": None, "role": "NEEDS DATA",
                        "why": "no readiness row found for this interest city",
                        "extensions": [], "risk": ""})
            continue
        cluster = _clean(d.get("City / Cluster"))
        members = [m.strip() for m in cluster.split("/")]
        extensions = [m for m in members
                      if m and not any(_city_match(m, [ic]) for ic in interest)]
        h, f = _lvl(d.get("Hotel Supply Readiness")), _lvl(d.get("Flight Route Readiness"))
        at = _lvl(d.get("Attractions / Tours Readiness"))
        h_txt = _clean(d.get("Hotel Supply Readiness")) or "missing"
        f_txt = _clean(d.get("Flight Route Readiness")) or "missing"
        at_txt = _clean(d.get("Attractions / Tours Readiness")) or "missing"
        risk = _clean(d.get("Campaign Risk"))
        cmin, pmin = SCORING["city_conversion_min"], SCORING["city_package_min"]
        if h is None or f is None:
            role = "NEEDS DATA"
            why = f"hotel readiness is '{h_txt}' and flight readiness is '{f_txt}' - cannot judge without this data"
        elif h >= cmin and f >= cmin:
            supply_risk = any(k in risk.lower() for k in ("supply", "depth", "sourcing"))
            role = "Conditional Conversion" if supply_risk else "Conversion"
            why = f"hotel ({h_txt}) and flight ({f_txt}) readiness both at or above the Medium bar"
            if supply_risk:
                why += f" - but known risk: '{risk}' - sourcing confirmation required before push"
        elif at is not None and at >= pmin:
            role = "Package"
            why = (f"attractions/tours readiness is strong ({at_txt}) but hotel ({h_txt}) or "
                   f"flight ({f_txt}) is below the Medium bar - suitable for packaged tours, not open-ended trips")
        else:
            role = "Content"
            why = (f"hotel ({h_txt}) and flight ({f_txt}) readiness below the Medium bar - "
                   f"inspiration content only, no conversion push")
        out.append({"city": city, "cluster": cluster if cluster.lower() != city.lower() else None,
                    "role": role, "why": why, "extensions": extensions, "risk": risk})
    return out


def roles_md(tables: dict, markets: list[str]) -> str:
    lines = ["Pre-computed city roles per market (Conditional/Conversion / Package / Content).",
             "Interest City = what this market's users actually search (recommend THIS city only). "
             "Readiness Cluster = how supply data is grouped. Cluster membership does NOT imply "
             "interest: other cluster members are extension candidates, never primary recommendations."]
    for m in markets:
        rs = city_roles(tables, m)
        if not rs:
            continue
        lines.append(f"- {m}:")
        for r in rs:
            cl = f" [readiness cluster: {r['cluster']}]" if r["cluster"] else ""
            ext = (f" Same-cluster extension candidate (no direct interest signal): "
                   + ", ".join(r["extensions"])) if r["extensions"] else ""
            lines.append(f"  - {r['city']}{cl} = {r['role']} ({r['why']}).{ext}")
    return "\n".join(lines)


def detect_conflicts(tables: dict) -> list[dict]:
    """Advisory role flags; weak readiness is not mislabeled as a data conflict.

    ROLE_TENSION  = demand exists but the safe selling role is Package/Content.
    READINESS_GAP = an interest city cannot be classified because supply data is absent.
    SUPPLY_RISK   = readiness passes but a known supply/depth risk needs verification.
    """
    flags = []
    for r in (tables.get("B_Markets") or []):
        mkt = _clean(r.get("Market"))
        for cr in city_roles(tables, mkt):
            if cr["role"] == "Conditional Conversion":
                ftype = "SUPPLY_RISK"
            elif cr["role"] == "NEEDS DATA":
                ftype = "READINESS_GAP"
            elif cr["role"] in ("Package", "Content"):
                ftype = "ROLE_TENSION"
            else:
                continue
            flags.append({"type": ftype, "table": "B_Markets x D_Cities",
                          "row": f"{mkt} x {cr['city']}", "field": "readiness", "raw": "",
                          "market": mkt, "city": cr["city"],
                          "cluster": cr["cluster"] or cr["city"], "why": cr["why"],
                          "detail": f"{mkt}: users actively search for {cr['city']}, but {cr['why']}. "
                                    f"Role auto-set to '{cr['role']}' - "
                                    + ("Sourcing to verify, PM to confirm" if ftype in ("SUPPLY_RISK", "READINESS_GAP")
                                       else "PM to confirm or override")})
    return flags


def dedupe_flags(flags: list[dict]) -> list[dict]:
    """Campaign-level view: role-tension flags sharing the same cluster and type collapse
    into ONE decision item listing all affected market x city pairs. Market packs keep
    the per-pair flags (each market's confirmation list needs its own row)."""
    grouped, out = {}, []
    for f in flags:
        if f["type"] in ("ROLE_TENSION", "READINESS_GAP", "SUPPLY_RISK") and f.get("cluster"):
            grouped.setdefault((f["type"], f["cluster"]), []).append(f)
        else:
            out.append(f)
    for (ftype, cluster), fs in grouped.items():
        if len(fs) == 1:
            out.append(fs[0])
            continue
        pairs = ", ".join(f"{f['market']} x {f['city']}" for f in fs)
        markets = sorted({f["market"] for f in fs})
        out.append({"type": ftype, "table": fs[0]["table"], "row": cluster,
                    "field": "readiness", "raw": "", "cluster": cluster,
                    "market": "/".join(markets), "city": cluster, "why": fs[0]["why"],
                    "detail": f"Cluster '{cluster}' [deduped x{len(fs)}]: {fs[0]['why']}. "
                              f"Affects {pairs} - ONE confirmation covers all of them. "
                              + ("Sourcing to verify, PM to confirm" if ftype in ("SUPPLY_RISK", "READINESS_GAP")
                                 else "PM to confirm or override")})
    return out


def market_code(market: str) -> str:
    """2-letter code for ID namespacing: prefer a 2-letter alias, else first 2 letters."""
    from .schema import alias_map
    aliases_all = alias_map()
    m = _clean(market).lower()
    for alias in sorted(aliases_all.get(m, set())):
        if len(alias) == 2:
            return alias.upper()
    for full, aliases in aliases_all.items():
        if m == full or m in aliases:
            for a in aliases | {full}:
                if len(a) == 2:
                    return a.upper()
    return m[:2].upper()


def asset_eligibility(tables: dict, market: str) -> dict:
    from .context import _covers
    from .schema import ENUM_COLUMNS
    out = {"eligible": [], "ambiguous": [], "not_eligible": []}
    for r in (tables.get("G_Assets") or []):
        name, cov = _clean(r.get("Asset Type")), _clean(r.get("Required Markets"))
        priority = _clean(r.get("Priority"))
        if not cov or cov.lower() in ("tbd", "n/a"):
            out["ambiguous"].append(f"{name} (markets TBD)")
        elif "selected" in cov.lower():
            out["ambiguous"].append(f"{name} (coverage '{cov}')")
        elif not _covers(cov, market):
            out["not_eligible"].append(f"{name} (markets: {cov})")
        elif priority not in ENUM_COLUMNS["Priority"]:
            out["ambiguous"].append(
                f"{name} (invalid/missing priority '{priority or 'empty'}')")
        else:
            out["eligible"].append(name)
    return out


def channel_eligibility(tables: dict, market: str) -> dict:
    """Classify every channel for one market: eligible / ambiguous / not eligible.
    Uses the same alias-aware coverage matching as the slicing layer."""
    from .context import _covers
    out = {"eligible": [], "ambiguous": [], "not_eligible": []}
    for r in (tables.get("E_Channels") or []):
        name, cov = _clean(r.get("Channel")), _clean(r.get("Market Coverage"))
        if "selected" in cov.lower():
            out["ambiguous"].append(f"{name} (coverage '{cov}' - owner: {_clean(r.get('Resource Owner'))})")
        elif _covers(cov, market):
            out["eligible"].append(name)
        else:
            out["not_eligible"].append(f"{name} (coverage: {cov})")
    return out


def eligibility_md(tables: dict, markets: list[str]) -> str:
    lines = ["Per-market channel AND asset eligibility (computed by the prototype from coverage "
             "columns - recommendations MUST stay inside these lists; anything not listed as "
             "eligible/ambiguous for a market may not be assigned to it):"]
    for m in markets:
        e = channel_eligibility(tables, m)
        a = asset_eligibility(tables, m)
        lines.append(f"- {m} (code {market_code(m)}):\n"
                     f"  - Channels ELIGIBLE: {', '.join(e['eligible']) or 'none'}. "
                     f"AMBIGUOUS - needs owner confirmation: {', '.join(e['ambiguous']) or 'none'}. "
                     f"NOT ELIGIBLE: {', '.join(e['not_eligible']) or 'none'}.\n"
                     f"  - Assets ELIGIBLE: {', '.join(a['eligible']) or 'none'}. "
                     f"AMBIGUOUS: {', '.join(a['ambiguous']) or 'none'}. "
                     f"NOT ELIGIBLE: {', '.join(a['not_eligible']) or 'none'}.")
    return "\n".join(lines)
